# Generated by Django 2.1.7 on 2019-02-12 16:35

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bookpic')),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='N', max_length=2)),
                ('isbn', isbn_field.fields.ISBNField(clean_isbn=False, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('author', models.CharField(max_length=120)),
            ],
        ),
    ]
